# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Assignment 11, Introduction to Statistics
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2015-03-27 Fri>
#+DESCRIPTION: First asssignment in the course Introduction to Statistics
#+KEYWORDS: Discrete Mathematics, assignment, bar chart, histogram
#+LANGUAGE: en
#+LaTeX_CLASS: article
#+LATEX_HEADER: \usepackage[usenames,dvipsnames]{color}
#+LATEX_HEADER: \usepackage[backend=bibtex, style=numeric]{biblatex}
#+LATEX_HEADER: \usepackage{commath}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{shapes,backgrounds}
#+LATEX_HEADER: \usepackage{marginnote}
#+LATEX_HEADER: \usepackage{listings}
#+LATEX_HEADER: \usepackage{color}
#+LATEX_HEADER: \usepackage{enumerate}
#+LATEX_HEADER: \hypersetup{urlcolor=blue}
#+LATEX_HEADER: \hypersetup{colorlinks,urlcolor=blue}
#+LATEX_HEADER: \addbibresource{bibliography.bib}
#+LATEX_HEADER: \setlength{\parskip}{16pt plus 2pt minus 2pt}
#+LATEX_HEADER: \definecolor{codebg}{rgb}{0.96,0.99,0.8}
#+LATEX_HEADER: \definecolor{codestr}{rgb}{0.46,0.09,0.2}

#+BEGIN_SRC emacs-lisp :exports none
(setq org-latex-pdf-process
        '("latexmk -pdflatex='pdflatex -shell-escape -interaction nonstopmode' -pdf -bibtex -f %f")
        org-latex-listings t
        org-src-fontify-natively t
        org-babel-latex-htlatex "htlatex")
(defmacro by-backend (&rest body)
    `(cl-case (when (boundp 'backend) (org-export-backend-name backend))
       ,@body))
#+END_SRC

#+RESULTS:
: by-backend

#+BEGIN_LATEX
  \lstset{ %
    backgroundcolor=\color{codebg},
    basicstyle=\ttfamily\scriptsize,
    breakatwhitespace=false,         % sets if automatic breaks should only happen at whitespace
    breaklines=false,
    captionpos=b,                    % sets the caption-position to bottom
    commentstyle=\color{mygreen},    % comment style
    framexleftmargin=10pt,
    xleftmargin=10pt,
    framerule=0pt,
    frame=tb,                        % adds a frame around the code
    keepspaces=true,                 % keeps spaces in text, useful for keeping indentation of code (possibly needs columns=flexible)
    keywordstyle=\color{blue},       % keyword style
    showspaces=false,                % show spaces everywhere adding particular underscores; it overrides 'showstringspaces'
    showstringspaces=false,          % underline spaces within strings only
    showtabs=false,                  % show tabs within strings adding particular underscores
    stringstyle=\color{codestr},     % string literal style
    tabsize=2,                       % sets default tabsize to 2 spaces
  }
#+END_LATEX

\clearpage

* Problems

** Problem 1
   Given the grades in an engineering faculty were as follows:

   #+NAME: students
   | lower | higher | graded |
   |-------+--------+--------|
   |    30 |     60 |     15 |
   |    60 |     75 |     45 |
   |    75 |     85 |     45 |
   |    85 |    100 |     15 |

   1. Present the data using a histogram.
   2. Calculate mode, median, algebraic average and variance.
   3. Calculate the number of students who earned at least 82 points.
   4. Given the following data for the preceding year for 80 students
      where the average grade was 70 and variance was 200, find the
      average and the variance for two years combined.

*** Answer 1

    #+NAME: students-histogram
    #+HEADER: :file images/students.pdf :width 10 :height 10
    #+HEADER: :exports both
    #+BEGIN_SRC R :results output graphics :var tbl=students
      library(ggplot2)
      tbl$avg <- (tbl$lower + tbl$higher) / 2
      ggplot(tbl) + 
          geom_histogram(
              aes(x = avg, weight = graded, fill = ..count..), 
              breaks = unique(append(tbl$lower, tbl$higher)),
              position = "identity", colour = "black") +
                  xlab("grades")
      
    #+END_SRC

    #+RESULTS: students-histogram
    [[file:images/assignments.pdf]]

*** Answer 2
    As easy to see from the diagram, there are two *modes*: one is in the
    (60, 75] range, an another is in the (75, 85] range.
    
    The *median* is the value at the 60'th studen, which is easy to see
    from the table as being the 75 points.
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          Md &= \frac{\frac{n}{2} - F(x_{m-1})}{f(x_m)} * (L_1-L_0)+L_0 \\
          Md &= \frac{\frac{120}{2} - 60}{45} * (85 - 75) + 75 \\
          Md &= \frac{60 - 60}{45} * (85 - 75) + 75 \\
          Md &= 75
        \end{aligned}
      \end{equation*}
    #+END_SRC

    The *average* is given by the formula:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          \frac{15 * \frac{30 + 60}{2} + 45 * \frac{60 + 75}{2} +
            45 * \frac{75 + 85}{2} + 15 * \frac{85 + 100}{2}}{15 + 45 + 45 + 15} = \\
          \frac{15 * 90 + 45 * 135 + 45 * 160 + 15 * 185}{2 * 120} = \\
          \frac{17400}{240} = \\72.5
        \end{aligned}
      \end{equation*}
    #+END_SRC

    And the *variance*:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          S^2 &= \frac{\sum_1^n (x - \overline{x})^2 * f(x)}{n} \\
          S^2 &= \frac{(45 - 72.5)^2 * 15 + (67.5 - 72.5)^2 * 45 +
            (80 - 72.5)^2 * 45 + (92.5 - 72.5)^2 * 15}{120} \\
          S^2 &= \frac{756.25 * 15 + 25 * 45 + 56.25 * 45 + 400 * 15}{120} \\
          S^2 &= \frac{21000}{120} \\
          S^2 &= 175
        \end{aligned}
      \end{equation*}
    #+END_SRC

*** Answer 3
    Using a slightly altered formula for the median, we can calculate the 82'nd
    percentile.  It is easy to see that the 82'nd percentile falls in the third
    group, viz. [75, 85) interval.  Assuming values are uniformly distribute
    in this interval, ${7 \over 10}$ of these are below 82 and ${3 \over 10}$
    are above.  In other words, we need to take 0.3 of the 45 students in this
    category, i.e. 13.5, together with 15 students who earned more points this
    gives roughly 19 students.

*** Answer 4
    New average is just the weighted average of both averages:
    $\frac{70*80+72.5*120}{80+120}=71.5$.

    The total variance is calculated using
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          s_1 &= n(S_1 + \overline{x}^2_1) \\
          s_1 &= 120 * (175 + 72.5^2) \\
          s_1 &= 651750. \\
          s_2 &= n(S_2 + \overline{x}^2_2) \\
          s_2 &= 80 * (200 + 70^2) \\
          s_2 &= 408000.
        \end{aligned}
      \end{equation*}
      \begin{equation*}
        \begin{aligned}
          S^2 &= \frac{s_1 + s_2}{n_1 + n_2} - \overline{x}^2 \\
          S^2 &= \frac{651750 + 408000}{200} - 71.5^2 \\
          S^2 &= \frac{651750 + 408000}{200} - 5112.25 \\
          S^2 &= 186.5
        \end{aligned}
      \end{equation*}
    #+END_SRC

** Problem 2
   Given the number of assignments submitted in 2009 (shown below):

   #+NAME: assignments
   | assignments | students |
   |-------------+----------|
   |           0 |       11 |
   |           1 |       18 |
   |           2 |       28 |
   |           3 |       22 |
   |           4 |       15 |
   |           5 |       16 |

   1. Draw a bar chart representing the data.
   2. Find mode, median, algebraic average and variance.
   3. In addition to the number of assignments submitted, students
      also received final grades.  Let $X$ be the number of assignments
      submitted, let $Y$ be the grade the student received.  Given also that
      Pearson coefficient is $r=0.75$.
      
      *Prove or disprove:*
      1. $Y = 0.75X + 96.25$.
      2. The number of assignments submitted negatively correlates with
         the final grade they received.
         
   4. An investigation found data on 10 more students.  5 of them didn't
      submit any assignment and 5 of them submitted 5 assignments each.
      Describe what will happen to each metric calculated in question 2 relying
      on the previously obtained values.

*** Answer 5
    #+NAME: assignments-histogram
    #+HEADER: :file images/assignments.pdf :width 10 :height 10
    #+HEADER: :exports both
    #+BEGIN_SRC R :results output graphics :var tbl=assignments
      library(ggplot2)
      ggplot(data = tbl, 
             aes(x = assignments, y = students, fill = assignments)) +
                 geom_bar(colour = "black", stat = "identity")
    #+END_SRC

    #+RESULTS: assignments-histogram
    [[file:images/assignments.pdf]]

*** Answer 6
    *Mode* for the assignments data is 2, i.e. most of the students submitted
    only two assignments.

    *Median* is $2+(3-2)/2=2.5$ (because there is an even number of bins).

    Weighted *average* can be obtained using
    $\frac{0*11+1*18+2*28+3*22+4*15+5*16}{110}=\frac{280}{110}=2.45(45)$.

    *Variance* can be obtained using:
    #+HEADER: :exports results
    #+HEADER: :results (by-backend (pdf "latex") (t "raw"))
    #+BEGIN_SRC latex
      \begin{equation*}
        \begin{aligned}
          S^2 &= \frac{(0 * 11)^2 + (1 * 18)^2 + (2 * 28)^2 +
            (3 * 22)^2 + (4 * 15)^2 + (5 * 16)^2}{110} - 2.45^2 \\
          S^2 &= \frac{17816}{110} - 6.0025 \\
          S^2 &= 161.963636364 \\
          S^2 &\simeq 162
        \end{aligned}
      \end{equation*}
    #+END_SRC
    
*** Answer 7
    While it seems appealing, it isn't really possible to have a determination
    coefficient predict the value of another variable with absolute certainity
    unless the coefficient is equal to one.  Thus $Y = 0.75X + 96.25$ is at best
    a lucky coincidence.

    Positive coefficient means that there exists positive correlation between
    two variables.  In particular, it means that roughly in three fourth of all
    cases the number of assignments submited perfectly predicted the final grade.
    So the claim is obviously false.

*** Answer 8
    After adding ten more observations the *mode* will not change as the
    observations fall into the bins which aren't as dense as the most dense one,
    i.e. the first bin will contain 11+5=16 students
    /(fewer than 28 of the densest bin)/ and 6+5=11 in the last bin.

    The *median* will not change either because we are adding observations to
    the outermost bins in an equal measure.

    The *average* will almost not change because the added observations will
    ``cancel out'', however, it will shift very slightly towards the upper
    end, since we increased the relative weight of the bin of those who
    submitted the most assignments.

    Since *variance* is affected by the mean, it is hard to tell without
    doing full recalculation whether it will or will not change.  However,
    since we added more borderline observations, which are most likely to
    be far away from the mean, we'd expect the variance to grow.
    
